events {
    worker_connections 1024;
}

http {
    upstream agent_backend {
        server agent:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://agent_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Tối ưu thời gian chờ kết nối
            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}
